(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const css=`
/* MOMOIROBARA FEATURES V4 */
.home-hero{min-height:250px!important;padding:32px 38px!important}.home-hero:after{pointer-events:none!important}
.momo-press{animation:momoPress .24s cubic-bezier(.16,1,.3,1)!important}@keyframes momoPress{0%{transform:scale(1)}45%{transform:scale(.92)}72%{transform:scale(1.045)}100%{transform:scale(1)}}
.momo-progress-input{height:20px!important;overflow:visible!important;clip-path:none!important;appearance:none!important;-webkit-appearance:none!important;background:transparent!important}.momo-progress-input::-webkit-slider-runnable-track{height:6px!important;border-radius:99px!important;background:linear-gradient(90deg,var(--a) 0,var(--b) var(--momo-p,0%),var(--track) var(--momo-p,0%),var(--track) 100%)!important;box-shadow:0 0 10px color-mix(in srgb,var(--a) 22%,transparent)!important}.momo-progress-input::-webkit-slider-thumb{-webkit-appearance:none!important;width:15px!important;height:15px!important;margin-top:-4.5px!important;border:3px solid var(--solid)!important;border-radius:50%!important;background:var(--a)!important;box-shadow:0 2px 10px color-mix(in srgb,var(--a) 38%,transparent)!important}.momo-progress-input::-moz-range-track{height:6px!important;border-radius:99px!important;background:var(--track)!important}.momo-progress-input::-moz-range-progress{height:6px!important;border-radius:99px!important;background:linear-gradient(90deg,var(--a),var(--b))!important}.momo-progress-input::-moz-range-thumb{width:15px!important;height:15px!important;border:3px solid var(--solid)!important;border-radius:50%!important;background:var(--a)!important}
.logo-flower{display:block!important;visibility:visible!important;opacity:1!important}.logo-flower .petal,.logo-flower .center{display:block!important}.momo-flower,.momo-flower-field,.momo-field-petal,.momo-floral-mark,.momo-floral-rule{display:none!important}
.momo-settings-gear{width:18px!important;height:18px!important;display:block!important;fill:none!important;stroke:currentColor!important;stroke-width:1.9!important;stroke-linecap:round!important;stroke-linejoin:round!important}
#momoMenuOpen,#momoMenuClose{position:fixed;width:40px;height:40px;place-items:center;z-index:10050;border:1px solid var(--border);border-radius:12px;background:var(--solid);color:var(--text);box-shadow:var(--shadow2)}#momoMenuClose{right:16px;top:16px;display:none}#momoMenuOpen{left:14px;top:14px;display:none}#momoMenuClose svg,#momoMenuOpen svg{width:19px;height:19px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round}@media(max-width:900px){#momoMenuOpen{display:grid!important}body.momo-menu-open #momoMenuOpen{display:none!important}body.momo-menu-open #momoMenuClose{display:grid!important}.side.momo-menu-closed{transform:translateX(-105%)!important}.side{transition:transform .3s cubic-bezier(.16,1,.3,1)!important}}
.momo-artist-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:14px;margin-top:18px}.momo-artist-card{border:1px solid var(--border);border-radius:18px;background:var(--solid);overflow:hidden;cursor:pointer;transition:transform .2s var(--ease),box-shadow .2s}.momo-artist-card:hover{transform:translateY(-4px);box-shadow:var(--shadow2)}.momo-artist-img{width:100%;aspect-ratio:1;object-fit:cover;display:block;background:linear-gradient(135deg,var(--a),var(--b))}.momo-artist-name{padding:11px 13px 3px;font-weight:800}.momo-artist-count{padding:0 13px 13px;color:var(--muted);font-size:12px}
.momo-lastfm-card{max-width:760px;margin-top:18px;padding:20px;border:1px solid var(--border);border-radius:20px;background:var(--solid);box-shadow:var(--shadow2)}.momo-lastfm-card h2{margin-bottom:5px}.momo-lastfm-card p{color:var(--muted);font-size:12px;margin-bottom:13px}.momo-lastfm-row{display:grid;gap:9px}.momo-lastfm-input{width:100%;padding:11px 13px;border:1px solid var(--border);border-radius:12px;background:var(--bg);color:var(--text)}.momo-lastfm-status{min-height:18px;margin-top:9px;color:var(--muted);font-size:12px}.momo-lastfm-auth{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}
`;
if(!$('#momoFeaturesStyles')){const st=document.createElement('style');st.id='momoFeaturesStyles';st.textContent=css;document.head.appendChild(st)}
const press=()=>{if(document.__momoPress)return;document.__momoPress=true;document.addEventListener('pointerdown',e=>{const b=e.target.closest?.('button,.tool,.pl-item,.song,.nav button,.side-action,.icon-btn,.primary,.secondary');if(!b)return;b.classList.remove('momo-press');void b.offsetWidth;b.classList.add('momo-press');setTimeout(()=>b.classList.remove('momo-press'),280)},{passive:true})};
const progress=()=>$$('input[type="range"]').forEach(r=>{if(!r.closest('.player,.player-bar,#playerBar,#nowPlayingBar'))return;r.classList.add('momo-progress-input');const max=Number(r.max)||0,val=Number(r.value)||0;r.style.setProperty('--momo-p',max?`${Math.max(0,Math.min(100,val/max*100))}%`:'0%')});
const settingsIcon=()=>$$('[aria-label="Settings"],[title="Settings"],.settings-button,.settings-btn,[data-action="settings"],.momo-settings-button').forEach(b=>{let svg=b.querySelector('svg');if(!svg){svg=document.createElementNS('http://www.w3.org/2000/svg','svg');b.replaceChildren(svg)}svg.setAttribute('viewBox','0 0 24 24');svg.classList.add('momo-settings-gear');svg.innerHTML='<path d="M9.1 3.7 9.8 2h4.4l.7 1.7 1.5.9 1.8-.3 2.2 3.8-1.1 1.4v1.8l1.1 1.4-2.2 3.8-1.8-.3-1.5.9-.7 1.7H9.8l-.7-1.7-1.5-.9-1.8.3-2.2-3.8 1.1-1.4V9.5L3.6 8.1l2.2-3.8 1.8.3 1.5-.9Z"/><circle cx="12" cy="10.4" r="2.7"/>'});
const menu=()=>{const side=$('.side');if(!side)return;let open=$('#momoMenuOpen'),close=$('#momoMenuClose');if(!open){open=document.createElement('button');open.id='momoMenuOpen';open.type='button';open.setAttribute('aria-label','Open menu');open.innerHTML='<svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/></svg>';document.body.appendChild(open)}if(!close){close=document.createElement('button');close.id='momoMenuClose';close.type='button';close.setAttribute('aria-label','Close menu');close.innerHTML='<svg viewBox="0 0 24 24"><path d="M6 6l12 12M18 6 6 18"/></svg>';document.body.appendChild(close)}if(!open.__momo){open.__momo=true;open.onclick=e=>{e.preventDefault();e.stopPropagation();side.classList.remove('momo-menu-closed');side.classList.add('open','show','active');document.body.classList.add('momo-menu-open')}}if(!close.__momo){close.__momo=true;close.onclick=e=>{e.preventDefault();e.stopPropagation();side.classList.add('momo-menu-closed');document.body.classList.remove('momo-menu-open')}}};
const activatePage=(p,b)=>{$$('.page').forEach(x=>x.classList.remove('active'));p.classList.add('active');$$('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active')};
const artists=()=>{const nav=$('.nav');if(!nav)return;let b=$('.momo-artists-nav');if(!b){b=document.createElement('button');b.type='button';b.className='momo-artists-nav';b.innerHTML='<span class="nav-icon"><svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><circle cx="17" cy="10" r="2"/><path d="M3 20c.5-4 2.4-6 6-6s5.5 2 6 6"/></svg></span><span>Artists</span>';nav.appendChild(b)}let p=$('#momoArtistsPage');if(!p){p=document.createElement('section');p.id='momoArtistsPage';p.className='page';p.innerHTML='<div class="library-top"><div><div class="eyebrow">Your collection</div><h1>Artists</h1></div></div><div class="momo-artist-grid"></div>';$('.content')?.appendChild(p)}const render=async()=>{const map=new Map();$$('.song').forEach(row=>{const a=$('.artist,.song-artist',row)?.textContent.trim();if(a)map.set(a,(map.get(a)||0)+1)});const g=$('.momo-artist-grid',p);g.innerHTML='';for(const [name,count] of [...map].sort((a,c)=>a[0].localeCompare(c[0]))){const card=document.createElement('article');card.className='momo-artist-card';card.innerHTML='<div class="momo-artist-img"></div><div class="momo-artist-name"></div><div class="momo-artist-count"></div>';$('.momo-artist-name',card).textContent=name;$('.momo-artist-count',card).textContent=`${count} track${count===1?'':'s'}`;g.appendChild(card);try{const j=await fetch('https://musicbrainz.org/ws/2/artist/?query='+encodeURIComponent('artist:"'+name+'"')+'&fmt=json&limit=1').then(r=>r.json());const id=j.artists?.[0]?.id;if(id){const a=await fetch('https://coverartarchive.org/artist/'+id).then(r=>r.json());const u=a.images?.[0]?.thumbnails?.large||a.images?.[0]?.image;if(u)$('.momo-artist-img',card).style.background=`url("${u}") center/cover`}}catch{}}};if(!b.__momo){b.__momo=true;b.onclick=e=>{e.preventDefault();e.stopImmediatePropagation();activatePage(p,b);render()}}};
const shuffle=()=>$$('.page').forEach(p=>{if($('.momo-shuffle',p)||!$('.songs',p))return;const h=$('.library-tools',p)||$('.head',p)||$('.library-top',p);if(!h)return;const b=document.createElement('button');b.type='button';b.className='tool momo-shuffle';b.textContent='Shuffle';b.onclick=()=>{const rows=$$('.song',p).sort(()=>Math.random()-.5);rows.forEach(r=>r.parentNode.appendChild(r));const play=rows[0]?.querySelector('button[aria-label*="play" i],.play-btn,.song-play');if(play)play.click()};h.appendChild(b)});
const LF='momoirobara.lastfm';const cfg=()=>{try{return JSON.parse(localStorage.getItem(LF)||'{}')}catch{return{}}};const save=v=>localStorage.setItem(LF,JSON.stringify(v));
const md5=async str=>{const k=[7,12,17,22,7,12,17,22,7,12,17,22,7,12,17,22,5,9,14,20,5,9,14,20,5,9,14,20,5,9,14,20,4,11,16,23,4,11,16,23,4,11,16,23,4,11,16,23,6,10,15,21,6,10,15,21,6,10,15,21,6,10,15,21],x=[];for(let i=0;i<64;i++)x[i]=Math.floor(4294967296*Math.abs(Math.sin(i+1)));const b=new TextEncoder().encode(str),l=((b.length+8>>>6)+1)*64,a=new Uint8Array(l);a.set(b);a[b.length]=128;const dv=new DataView(a.buffer);dv.setUint32(l-8,b.length*8,true);let A=1732584193,B=4023233417,C=2562383102,D=271733878;for(let o=0;o<l;o+=64){const M=[];for(let j=0;j<16;j++)M[j]=dv.getUint32(o+j*4,true);let aa=A,bb=B,cc=C,dd=D;for(let i=0;i<64;i++){let f,g;if(i<16){f=(bb&cc)|((~bb)&dd);g=i}else if(i<32){f=(dd&bb)|((~dd)&cc);g=(5*i+1)%16}else if(i<48){f=bb^cc^dd;g=(3*i+5)%16}else{f=cc^(bb|(~dd));g=(7*i)%16}const z=(aa+f+x[i]+M[g])>>>0;aa=dd;dd=cc;cc=bb;bb=(bb+((z<<k[i])|(z>>>(32-k[i]))))>>>0}A=(A+aa)>>>0;B=(B+bb)>>>0;C=(C+cc)>>>0;D=(D+dd)>>>0}return[A,B,C,D].map(n=>n.toString(16).padStart(8,'0').match(/../g).reverse().join('')).join('')};
const lfCall=async(method,params={})=>{const c=cfg();if(!c.key||!c.secret||!c.session)return null;const p={...params,api_key:c.key,method,sk:c.session};p.api_sig=await md5(Object.keys(p).sort().map(k=>k+p[k]).join('')+c.secret);p.format='json';return fetch('https://ws.audioscrobbler.com/2.0/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(p)}).catch(()=>null)};
const lastfm=()=>{const nav=$('.nav');if(!nav)return;let b=$('.momo-lastfm-nav');if(!b){b=document.createElement('button');b.type='button';b.className='momo-lastfm-nav';b.innerHTML='<span class="nav-icon" style="font-size:10px;font-weight:900">LF</span><span>Last.fm</span>';nav.appendChild(b)}let p=$('#momoLastFmPage');if(!p){p=document.createElement('section');p.id='momoLastFmPage';p.className='page';p.innerHTML='<div class="library-top"><div><div class="eyebrow">Account</div><h1>Last.fm</h1></div></div><div class="momo-lastfm-card"><h2>Last.fm scrobbling</h2><p>Connect Last.fm to send now-playing and completed-track scrobbles.</p><div class="momo-lastfm-row"><input class="momo-lastfm-input" data-lf="key" placeholder="API key"><input class="momo-lastfm-input" data-lf="secret" type="password" placeholder="Shared secret"><input class="momo-lastfm-input" data-lf="session" type="password" placeholder="Session key"><div class="momo-lastfm-auth"><button class="primary" data-lf-save>Save</button><a class="secondary" href="https://www.last.fm/api/account/create" target="_blank" rel="noreferrer">Get API key</a></div><div class="momo-lastfm-status" data-lf-status></div></div></div>';$('.content')?.appendChild(p)}const c=cfg();$$('[data-lf]',p).forEach(i=>i.value=c[i.dataset.lf]||'');if(!b.__momo){b.__momo=true;b.onclick=e=>{e.preventDefault();e.stopImmediatePropagation();activatePage(p,b)}}q('[data-lf-save]',p).onclick=()=>{const v={};$$('[data-lf]',p).forEach(i=>v[i.dataset.lf]=i.value.trim());save(v);q('[data-lf-status]',p).textContent=v.key&&v.secret&&v.session?'Last.fm scrobbling enabled.':'Enter all three Last.fm values.'}};
const scrobble=()=>{const a=$('audio');if(!a||a.__momoLF)return;a.__momoLF=true;let done=false;const info=()=>{const p=$('.player,.player-bar,#playerBar,#nowPlayingBar');return{artist:$('.artist,.song-artist,.now-playing-artist',p)?.textContent.trim()||'',track:$('.title,.song-title,.now-playing-title',p)?.textContent.trim()||'',album:$('.album,.song-album,.now-playing-album',p)?.textContent.trim()||''}};a.addEventListener('play',()=>{done=false;const t=info();if(t.artist&&t.track)lfCall('track.updateNowPlaying',t)});a.addEventListener('timeupdate',()=>{if(done||!a.duration||a.currentTime<Math.min(a.duration/2,240))return;done=true;const t=info();if(t.artist&&t.track)lfCall('track.scrobble',{...t,timestamp:Math.floor(Date.now()/1000)})})};
const density=()=>{$$('label,div,span,p').forEach(e=>{if(e.children.length)return;if(/interface\s+density/i.test(e.textContent.trim())){const row=e.closest('.setting,.setting-row,.setting-item,.control-row,.setting-group');if(row)row.remove();else e.remove()}})};
const init=()=>{press();progress();settingsIcon();menu();artists();shuffle();lastfm();scrobble();density();document.addEventListener('input',progress,true);document.addEventListener('change',progress,true)};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();new MutationObserver(()=>{progress();settingsIcon();menu();artists();shuffle();lastfm();scrobble();density()}).observe(document.body,{childList:true,subtree:true});
})();
