(()=>{
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const css=`
/* MOMOIROBARA FEATURES: LAST.FM ONLY */
.momo-safe-pressed{animation:momoSafePress .22s cubic-bezier(.16,1,.3,1)}
@keyframes momoSafePress{0%{transform:scale(1)}45%{transform:scale(.94)}75%{transform:scale(1.035)}100%{transform:scale(1)}}
.momo-artist-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:14px;margin-top:18px}.momo-artist-card{border:1px solid var(--border);border-radius:18px;background:var(--solid);overflow:hidden;cursor:pointer;transition:transform .2s ease}.momo-artist-card:hover{transform:translateY(-4px)}.momo-artist-img{display:block;width:100%;aspect-ratio:1;object-fit:cover;background:linear-gradient(135deg,var(--a),var(--b))}.momo-artist-name{padding:11px 13px 3px;font-weight:800}.momo-artist-count{padding:0 13px 13px;color:var(--muted);font-size:12px}.momo-artist-search{width:min(420px,100%);padding:10px 13px;border:1px solid var(--border);border-radius:12px;background:var(--solid);color:var(--text)}.momo-lastfm-card{margin-top:16px;padding:18px;border:1px solid var(--border);border-radius:18px;background:var(--solid)}.momo-lastfm-card p{color:var(--muted);font-size:12px}.momo-lastfm-row{display:flex;gap:8px;flex-wrap:wrap}.momo-lastfm-input{flex:1;min-width:180px;padding:10px 12px;border:1px solid var(--border);border-radius:11px;background:var(--bg);color:var(--text)}
`;
if(!q('#momoFeaturesStyles')){const st=document.createElement('style');st.id='momoFeaturesStyles';st.textContent=css;document.head.appendChild(st)}
if(!document.__momoPress){document.__momoPress=true;document.addEventListener('pointerdown',e=>{const b=e.target.closest?.('button,.tool,.pl-item,.song,.nav button,.side-action,.icon-btn,.primary,.secondary');if(!b)return;b.classList.remove('momo-safe-pressed');void b.offsetWidth;b.classList.add('momo-safe-pressed');setTimeout(()=>b.classList.remove('momo-safe-pressed'),240)},{passive:true})}
const addShuffle=()=>qa('.page').forEach(page=>{if(q('.momo-shuffle',page)||!qa('.song',page).length)return;const host=q('.library-tools',page)||q('.head',page)||q('.library-top',page);if(!host)return;const b=document.createElement('button');b.type='button';b.className='tool momo-shuffle';b.textContent='Shuffle';b.onclick=()=>{const rows=qa('.song',page).sort(()=>Math.random()-.5);const box=rows[0]?.parentElement;rows.forEach(r=>box?.appendChild(r));(rows[0]?.querySelector('.play-btn,.song-play,[data-action="play"],button')||rows[0])?.click()};host.appendChild(b)});
const addArtists=()=>{let nav=qa('.nav button').find(b=>/artists/i.test(b.textContent));if(!nav){const n=q('.nav');if(!n)return;nav=document.createElement('button');nav.type='button';nav.innerHTML='<span>Artists</span>';n.appendChild(nav)}let page=q('#momoArtistsPage');if(!page){page=document.createElement('section');page.id='momoArtistsPage';page.className='page';page.innerHTML='<div class="library-top"><div><div class="eyebrow">Your collection</div><h1>Artists</h1></div><input class="momo-artist-search" placeholder="Search artists..."></div><div class="momo-artist-grid"></div>';q('.content')?.appendChild(page)}const render=()=>{const map=new Map();qa('.song').forEach(row=>{const artist=q('.artist,.song-artist',row)?.textContent.trim();if(artist)map.set(artist,(map.get(artist)||0)+1)});const term=q('.momo-artist-search',page)?.value.toLowerCase()||'',grid=q('.momo-artist-grid',page);grid.innerHTML='';[...map].filter(([a])=>a.toLowerCase().includes(term)).sort().forEach(([name,count])=>{const card=document.createElement('article');card.className='momo-artist-card';card.innerHTML='<div class="momo-artist-img"></div><div class="momo-artist-name"></div><div class="momo-artist-count"></div>';q('.momo-artist-name',card).textContent=name;q('.momo-artist-count',card).textContent=`${count} track${count===1?'':'s'}`;card.onclick=async()=>{try{const mb=await fetch('https://musicbrainz.org/ws/2/artist/?query='+encodeURIComponent('artist:"'+name+'"')+'&fmt=json&limit=1').then(r=>r.json());const id=mb.artists?.[0]?.id;if(!id)return;const ca=await fetch('https://coverartarchive.org/artist/'+id).then(r=>r.json()).catch(()=>null);const image=ca?.images?.[0]?.thumbnails?.large||ca?.images?.[0]?.image;if(image)q('.momo-artist-img',card).style.background=`url("${image}") center/cover`;}catch{}};grid.appendChild(card)})};nav.addEventListener('click',e=>{e.preventDefault();qa('.page').forEach(p=>p.classList.remove('active'));page.classList.add('active');render()});q('.momo-artist-search',page)?.addEventListener('input',render);render()};
// Last.fm only. User supplies their own API key, shared secret and session key.
const STORE='momoirobara.lastfm';const cfg=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return{}}};const save=v=>localStorage.setItem(STORE,JSON.stringify(v));
const digest=async text=>{const data=new TextEncoder().encode(text),hash=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('')};
const lf=async(method,params={})=>{const c=cfg();if(!c.apiKey||!c.sessionKey)return null;const p={...params,api_key:c.apiKey,method,sk:c.sessionKey};const sig=await digest(Object.keys(p).sort().map(k=>k+p[k]).join('')+(c.secret||''));p.api_sig=sig;p.format='json';return fetch('https://ws.audioscrobbler.com/2.0/',{method:'POST',body:new URLSearchParams(p)}).then(r=>r.json())};
const current=()=>{const p=q('.player,.player-bar,#playerBar,#nowPlayingBar');return{track:q('.title,.song-title,.now-playing-title',p)?.textContent.trim()||'',artist:q('.artist,.song-artist,.now-playing-artist',p)?.textContent.trim()||'',album:q('.album,.song-album,.now-playing-album',p)?.textContent.trim()||''}};
const nowPlaying=async()=>{const t=current();if(!t.track||!t.artist)return;await lf('track.updateNowPlaying',{artist:t.artist,track:t.track,album:t.album});clearTimeout(window.__momoLastFmTimer);window.__momoLastFmTimer=setTimeout(()=>lf('track.scrobble',{artist:t.artist,track:t.track,album:t.album,timestamp:Math.floor(Date.now()/1000)}),Math.min(Math.max((q('audio')?.duration||240)*500,30000),240000))};
const lastfmUI=()=>{const page=qa('.page').find(p=>/settings/i.test(p.id+' '+(q('h1,h2',p)?.textContent||'')));if(!page||q('.momo-lastfm-card',page))return;const c=document.createElement('div');c.className='momo-lastfm-card';c.innerHTML='<h3>Last.fm scrobbling</h3><p>Enter your Last.fm API key, shared secret and session key. Values stay in this browser.</p><div class="momo-lastfm-row"><input class="momo-lastfm-input" placeholder="API key"><input class="momo-lastfm-input" type="password" placeholder="Shared secret"><input class="momo-lastfm-input" type="password" placeholder="Session key"><button class="primary">Save</button></div><p class="momo-lastfm-status"></p>';page.appendChild(c);const inputs=qa('input',c),old=cfg();inputs[0].value=old.apiKey||'';inputs[1].value=old.secret||'';inputs[2].value=old.sessionKey||'';q('button',c).onclick=()=>{save({apiKey:inputs[0].value.trim(),secret:inputs[1].value.trim(),sessionKey:inputs[2].value.trim()});q('.momo-lastfm-status',c).textContent='Last.fm settings saved.'}};
const audio=()=>{const a=q('audio');if(!a||a.__momoLastFm)return;a.__momoLastFm=true;a.addEventListener('play',nowPlaying);a.addEventListener('loadedmetadata',()=>{if(!a.paused)nowPlaying()})};
const init=()=>{addShuffle();addArtists();lastfmUI();audio()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();new MutationObserver(()=>{addShuffle();addArtists();lastfmUI();audio()}).observe(document.body,{childList:true,subtree:true});
})();
