(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const css=`
/* MOMOIROBARA FEATURES V3 */
.momo-press{animation:momoPress .24s cubic-bezier(.16,1,.3,1)}@keyframes momoPress{0%{transform:scale(1)}45%{transform:scale(.93)}75%{transform:scale(1.035)}100%{transform:scale(1)}}
.momo-progress-input{height:20px!important;overflow:visible!important;clip-path:none!important;appearance:none!important;-webkit-appearance:none!important;background:transparent!important}.momo-progress-input::-webkit-slider-runnable-track{height:6px!important;border-radius:99px!important;background:linear-gradient(90deg,var(--a),var(--b) var(--momo-p,0%),var(--track) var(--momo-p,0%))!important;box-shadow:0 0 9px color-mix(in srgb,var(--a) 25%,transparent)!important}.momo-progress-input::-webkit-slider-thumb{-webkit-appearance:none!important;width:14px!important;height:14px!important;margin-top:-4px!important;border:3px solid var(--solid)!important;border-radius:50%!important;background:var(--a)!important;box-shadow:0 2px 9px color-mix(in srgb,var(--a) 35%,transparent)!important}.momo-progress-input::-moz-range-track{height:6px!important;border-radius:99px!important;background:var(--track)!important}.momo-progress-input::-moz-range-progress{height:6px!important;border-radius:99px!important;background:linear-gradient(90deg,var(--a),var(--b))!important}
.logo-flower,.home-hero{display:block!important;visibility:visible!important;opacity:1!important}.logo-flower .petal,.logo-flower .center{display:block!important}.momo-flower,.momo-flower-field,.momo-field-petal,.momo-floral-mark,.momo-floral-rule{display:none!important}
.momo-settings-gear{width:18px!important;height:18px!important;display:block!important;fill:none!important;stroke:currentColor!important;stroke-width:1.9!important;stroke-linecap:round!important;stroke-linejoin:round!important}
.momo-artist-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:14px;margin-top:18px}.momo-artist-card{border:1px solid var(--border);border-radius:18px;background:var(--solid);overflow:hidden;cursor:pointer;transition:.2s}.momo-artist-card:hover{transform:translateY(-4px);box-shadow:var(--shadow2)}.momo-artist-img{width:100%;aspect-ratio:1;object-fit:cover;display:block;background:linear-gradient(135deg,var(--a),var(--b))}.momo-artist-name{padding:11px 13px 3px;font-weight:800}.momo-artist-count{padding:0 13px 13px;color:var(--muted);font-size:12px}
.momo-lastfm-card{max-width:760px;margin-top:18px;padding:20px;border:1px solid var(--border);border-radius:20px;background:var(--solid);box-shadow:var(--shadow2)}.momo-lastfm-card h2{margin-bottom:5px}.momo-lastfm-card p{color:var(--muted);font-size:12px;margin-bottom:13px}.momo-lastfm-row{display:grid;gap:9px}.momo-lastfm-input{width:100%;padding:11px 13px;border:1px solid var(--border);border-radius:12px;background:var(--bg);color:var(--text)}.momo-lastfm-status{min-height:18px;margin-top:9px;color:var(--muted);font-size:12px}
#momoMenuClose,#momoMenuOpen{position:fixed;width:40px;height:40px;place-items:center;z-index:10050;border:1px solid var(--border);border-radius:12px;background:var(--solid);color:var(--text);box-shadow:var(--shadow2)}#momoMenuClose{right:16px;top:16px;display:none}#momoMenuOpen{left:14px;top:14px;display:none}#momoMenuClose svg,#momoMenuOpen svg{width:19px;height:19px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round}@media(max-width:900px){#momoMenuOpen{display:grid!important}body.momo-menu-open #momoMenuOpen{display:none!important}body.momo-menu-open #momoMenuClose{display:grid!important}}
`;
if(!$('#momoFeaturesStyles')){const st=document.createElement('style');st.id='momoFeaturesStyles';st.textContent=css;document.head.appendChild(st)}

const press=()=>{if(document.__momoPress)return;document.__momoPress=true;document.addEventListener('pointerdown',e=>{const b=e.target.closest?.('button,.tool,.pl-item,.song,.nav button,.side-action,.icon-btn,.primary,.secondary');if(!b)return;b.classList.remove('momo-press');void b.offsetWidth;b.classList.add('momo-press');setTimeout(()=>b.classList.remove('momo-press'),260)},{passive:true})};
const progress=()=>$$('input[type="range"]').forEach(r=>{if(!r.closest('.player,.player-bar,#playerBar,#nowPlayingBar'))return;r.classList.add('momo-progress-input');const max=Number(r.max)||0,val=Number(r.value)||0;r.style.setProperty('--momo-p',max?`${Math.max(0,Math.min(100,val/max*100))}%`:'0%')});
const settingsIcon=()=>$$('[aria-label="Settings"],[title="Settings"],.settings-button,.settings-btn,[data-action="settings"],.momo-settings-button').forEach(b=>{let svg=b.querySelector('svg');if(!svg){svg=document.createElementNS('http://www.w3.org/2000/svg','svg');b.replaceChildren(svg)}svg.setAttribute('viewBox','0 0 24 24');svg.classList.add('momo-settings-gear');svg.innerHTML='<path d="M9.1 3.7 9.8 2h4.4l.7 1.7 1.5.9 1.8-.3 2.2 3.8-1.1 1.4v1.8l1.1 1.4-2.2 3.8-1.8-.3-1.5.9-.7 1.7H9.8l-.7-1.7-1.5-.9-1.8.3-2.2-3.8 1.1-1.4V9.5L3.6 8.1l2.2-3.8 1.8.3 1.5-.9Z"/><circle cx="12" cy="10.4" r="2.7"/>'});
const menu=()=>{const side=$('.side');if(!side)return;let open=$('#momoMenuOpen'),close=$('#momoMenuClose');if(!open){open=document.createElement('button');open.id='momoMenuOpen';open.type='button';open.setAttribute('aria-label','Open menu');open.innerHTML='<svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/></svg>';document.body.appendChild(open)}if(!close){close=document.createElement('button');close.id='momoMenuClose';close.type='button';close.setAttribute('aria-label','Close menu');close.innerHTML='<svg viewBox="0 0 24 24"><path d="M6 6l12 12M18 6 6 18"/></svg>';document.body.appendChild(close)}if(!open.__momo){open.__momo=true;open.onclick=e=>{e.preventDefault();side.classList.add('open','show','active');document.body.classList.add('momo-menu-open')}}if(!close.__momo){close.__momo=true;close.onclick=e=>{e.preventDefault();e.stopPropagation();side.classList.remove('open','show','active');document.body.classList.remove('momo-menu-open')}}const sync=()=>document.body.classList.toggle('momo-menu-open',['open','show','active'].some(c=>side.classList.contains(c)));if(!side.__momoObs){side.__momoObs=true;new MutationObserver(sync).observe(side,{attributes:true,attributeFilter:['class']})}sync()};
const activatePage=(p,b)=>{$$('.page').forEach(x=>x.classList.remove('active'));p.classList.add('active');$$('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active')};
const artists=()=>{const nav=$('.nav');if(!nav)return;let b=$('.momo-artists-nav');if(!b){b=document.createElement('button');b.type='button';b.className='momo-artists-nav';b.innerHTML='<span class="nav-icon"><svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><circle cx="17" cy="10" r="2"/><path d="M3 20c.5-4 2.4-6 6-6s5.5 2 6 6"/></svg></span><span>Artists</span>';nav.appendChild(b)}let p=$('#momoArtistsPage');if(!p){p=document.createElement('section');p.id='momoArtistsPage';p.className='page';p.innerHTML='<div class="library-top"><div><div class="eyebrow">Your collection</div><h1>Artists</h1></div></div><div class="momo-artist-grid"></div>';$('.content')?.appendChild(p)}const render=()=>{const map=new Map();$$('.song').forEach(row=>{const a=$('.artist,.song-artist',row)?.textContent.trim();if(a)map.set(a,(map.get(a)||0)+1)});const g=$('.momo-artist-grid',p);g.innerHTML='';[...map].sort((a,c)=>a[0].localeCompare(c[0])).forEach(([name,count])=>{const card=document.createElement('article');card.className='momo-artist-card';card.innerHTML='<div class="momo-artist-img"></div><div class="momo-artist-name"></div><div class="momo-artist-count"></div>';$('.momo-artist-name',card).textContent=name;$('.momo-artist-count',card).textContent=`${count} track${count===1?'':'s'}`;card.onclick=async()=>{try{const j=await fetch('https://musicbrainz.org/ws/2/artist/?query='+encodeURIComponent('artist:"'+name+'"')+'&fmt=json&limit=1').then(r=>r.json());const id=j.artists?.[0]?.id;if(!id)return;const a=await fetch('https://coverartarchive.org/artist/'+id).then(r=>r.json());const u=a.images?.[0]?.thumbnails?.large||a.images?.[0]?.image;if(u)$('.momo-artist-img',card).style.background=`url("${u}") center/cover`;}catch{}};g.appendChild(card)})};if(!b.__momo){b.__momo=true;b.onclick=e=>{e.preventDefault();e.stopImmediatePropagation();activatePage(p,b);render()}}render()};
const shuffle=()=>$$('.page').forEach(p=>{if($('.momo-shuffle',p)||!$('.songs',p))return;const h=$('.library-tools',p)||$('.head',p)||$('.library-top',p);if(!h)return;const b=document.createElement('button');b.type='button';b.className='tool momo-shuffle';b.textContent='Shuffle';b.onclick=()=>{const rows=$$('.song',p);rows.sort(()=>Math.random()-.5).forEach(r=>r.parentNode.appendChild(r));rows[0]?.querySelector('button')?.click()};h.appendChild(b)});
const LF='momoirobara.lastfm';const cfg=()=>{try{return JSON.parse(localStorage.getItem(LF)||'{}')}catch{return{}}};const save=v=>localStorage.setItem(LF,JSON.stringify(v));
const md5=async s=>{const r=await fetch('https://api.hashify.net/hash/md5/hex?value='+encodeURIComponent(s));return (await r.json()).Digest};
const lastfm=()=>{const nav=$('.nav');if(!nav)return;let b=$('.momo-lastfm-nav');if(!b){b=document.createElement('button');b.type='button';b.className='momo-lastfm-nav';b.innerHTML='<span class="nav-icon">LF</span><span>Last.fm</span>';nav.appendChild(b)}let p=$('#momoLastFmPage');if(!p){p=document.createElement('section');p.id='momoLastFmPage';p.className='page';p.innerHTML='<div class="library-top"><div><div class="eyebrow">Account</div><h1>Last.fm</h1></div></div><div class="momo-lastfm-card"><h2>Last.fm scrobbling</h2><p>Enter your Last.fm API key, shared secret, and session key. They are stored only in this browser.</p><div class="momo-lastfm-row"><input class="momo-lastfm-input" data-lf="key" placeholder="API key"><input class="momo-lastfm-input" data-lf="secret" type="password" placeholder="Shared secret"><input class="momo-lastfm-input" data-lf="session" type="password" placeholder="Session key"><button class="primary" data-lf-save>Save</button><div class="momo-lastfm-status" data-lf-status></div></div></div>';$('.content')?.appendChild(p)}const c=cfg();$$('[data-lf]',p).forEach(i=>i.value=c[i.dataset.lf]||'');if(!b.__momo){b.__momo=true;b.onclick=e=>{e.preventDefault();e.stopImmediatePropagation();activatePage(p,b)}}q('[data-lf-save]',p).onclick=()=>{const v={};$$('[data-lf]',p).forEach(i=>v[i.dataset.lf]=i.value.trim());save(v);q('[data-lf-status]',p).textContent='Last.fm settings saved.'}};
const lfSubmit=async(method,params)=>{const c=cfg();if(!c.key||!c.secret||!c.session)return;const p={...params,api_key:c.key,method,sk:c.session};const sig=await md5(Object.keys(p).sort().map(k=>k+p[k]).join('')+c.secret);p.api_sig=sig;p.format='json';return fetch('https://ws.audioscrobbler.com/2.0/',{method:'POST',body:new URLSearchParams(p)}).catch(()=>null)};
const scrobble=()=>{const a=$('audio');if(!a||a.__momoLF)return;a.__momoLF=true;let done=false;const info=()=>{const p=$('.player,.player-bar,#playerBar,#nowPlayingBar');return{artist:$('.artist,.song-artist,.now-playing-artist',p)?.textContent.trim()||'',track:$('.title,.song-title,.now-playing-title',p)?.textContent.trim()||'',album:$('.album,.song-album,.now-playing-album',p)?.textContent.trim()||''}};a.onplay=()=>{done=false;const t=info();if(t.artist&&t.track)lfSubmit('track.updateNowPlaying',t)};a.ontimeupdate=()=>{if(done||!a.duration||a.currentTime<Math.min(a.duration/2,240))return;done=true;const t=info();if(t.artist&&t.track)lfSubmit('track.scrobble',{...t,timestamp:Math.floor(Date.now()/1000)})}};
const init=()=>{press();progress();settingsIcon();menu();artists();shuffle();lastfm();scrobble();document.addEventListener('input',progress,true);document.addEventListener('change',progress,true)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();new MutationObserver(()=>{progress();settingsIcon();menu();artists();shuffle();lastfm();scrobble()}).observe(document.body,{childList:true,subtree:true});
})();
