/* Momoirobara experimental lyrics UI bridge. Keeps the original lyrics UI. */
(async () => {
  'use strict';
  if (window.__momoExperimentalLyrics) return;
  window.__momoExperimentalLyrics = true;
  const state={audio:null,lyrics:null,trackKey:'',manager:null,metadataResolver:null,timer:0,abort:null,loading:false,activeRow:null};
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  const findRoot=()=>document.getElementById('lyr')||document.querySelector('.lyrics-drawer #lyr')||document.querySelector('.lyrics-drawer');
  function css(){if(document.getElementById('momo-experimental-lyrics-css'))return;const s=document.createElement('style');s.id='momo-experimental-lyrics-css';s.textContent=`#momoExperimentalLyricsStatus{position:fixed;right:18px;bottom:24px;z-index:99997;font:500 11px system-ui;color:var(--muted,#777);pointer-events:none;opacity:0;transition:opacity .2s}#momoExperimentalLyricsStatus.show{opacity:.9}#lyr .momo-word.active{color:var(--a,#c86a9c);opacity:1}`;document.head.appendChild(s)}
  function toast(text){let e=document.getElementById('momoExperimentalLyricsStatus');if(!e){e=document.createElement('div');e.id='momoExperimentalLyricsStatus';document.body.appendChild(e)}e.textContent=text;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1800)}
  function parseFilename(url){try{const n=decodeURIComponent(new URL(url,location.href).pathname.split('/').pop()||'').replace(/\.[^.]+$/,'').replace(/[_]+/g,' ').replace(/\s+/g,' ').trim(),p=n.split(/\s+[-–—]\s+/);return p.length>=2?{artist:p[0].trim(),title:p.slice(1).join(' - ').trim()}:{title:n}}catch{return{}}}
  function readTrack(){const a=state.audio||document.querySelector('audio');if(!a)return null;state.audio=a;const songs=Array.isArray(window.momoSongs)?window.momoSongs:[],index=Number(window.momoCurrentIndex),appSong=Number.isInteger(index)&&index>=0?songs[index]:null,te=document.querySelector('[data-track-title],.now-playing .title,.player .title,.player-bar .title,[class*="now-playing"] [class*="title"]'),ae=document.querySelector('[data-track-artist],.now-playing .artist,.player .artist,.player-bar .artist'),f=parseFilename(a.currentSrc||a.src||appSong?.fileName||appSong?.path||''),base=appSong?.metadata||appSong||{},title=String(base.title||base.trackName||te?.textContent||f.title||'').trim(),artist=String(base.artist||base.artistName||ae?.textContent||f.artist||'').trim(),duration=Number(base.duration||a.duration||0);return{...appSong,fileName:appSong?.fileName||appSong?.path||a.currentSrc||a.src||'',metadata:{...base,title,artist,album:String(base.album||base.albumName||'').trim(),duration:Number.isFinite(duration)?duration:0,isrc:base.isrc||base.ISRC||''},title,artist,duration}}
  async function im(p){try{return await import(p)}catch(e){console.warn('[momo lyrics]',p,e);return null}}
  async function getManager(){if(state.manager)return state.manager;const m=await im('./manager.js');if(!m?.createLyricsManager)return null;const specs=[['./providers/lyricsplus.js','lyricsPlusProvider'],['./providers/lrclib.js','lrclibProvider'],['./providers/lrcmux.js','lrcMuxProvider']],ps=[];for(const[p,n]of specs){const x=await im(p),v=x?.default||x?.[n];if(v?.getLyrics)ps.push(v)}state.manager=m.createLyricsManager({providers:ps,delayMs:600});return state.manager}
  async function resolveMetadata(track,signal){if(!state.metadataResolver){const mod=await im('./metadata-pipeline.js');state.metadataResolver=mod?.resolveTrackForLyrics||null}return state.metadataResolver?state.metadataResolver(track,{signal}):track}
  function persistRecoveredMetadata(track){try{const songs=Array.isArray(window.momoSongs)?window.momoSongs:[],index=Number(window.momoCurrentIndex),song=Number.isInteger(index)&&index>=0?songs[index]:null;if(!song||!track?.metadata)return;const m=track.metadata;song.metadata={...(song.metadata||{}),...m};for(const k of ['title','artist','album','duration','isrc','musicbrainzId'])if(m[k]!==undefined&&m[k]!==null&&String(m[k]).trim()!=='')song[k]=m[k];window.momoSongs=songs;window.dispatchEvent(new CustomEvent('momo:metadata-recovered',{detail:{index,metadata:m}}))}catch(e){console.warn('[momo metadata persist]',e)}}
  function render(l){const root=findRoot();if(!root)return;root.classList.remove('momo-experimental-owned','momo-amll');root.dataset.wordTiming=l?.wordTiming||'none';root.innerHTML='';const lines=Array.isArray(l?.lines)?l.lines:[];if(!lines.length){root.textContent=l?.plainLyrics||'No lyrics found.';return}lines.forEach((line,i)=>{const row=document.createElement('div');row.className='line';row.dataset.index=i;row.dataset.start=String(Number(line.start)||0);row.dataset.end=String(Number(line.end)||0);if(Array.isArray(line.words)&&line.words.length){line.words.forEach((w,j)=>{const span=document.createElement('span');span.className='momo-word';span.textContent=String(w.text||'')+(j===line.words.length-1?'':' ');span.dataset.start=String(Number(w.start));span.dataset.end=String(Number(w.end));row.appendChild(span)})}else row.textContent=line.text||'';row.onclick=()=>{if(state.audio&&Number.isFinite(Number(line.start)))state.audio.currentTime=Number(line.start)};root.appendChild(row)})}
  function tick(){const root=findRoot(),a=state.audio;if(!root||!a||!state.lyrics)return;const t=a.currentTime||0;let active=null;root.querySelectorAll('.line').forEach(row=>{const s=Number(row.dataset.start),e=Number(row.dataset.end);const on=Number.isFinite(s)&&t>=s&&(!e||t<e);row.classList.toggle('active',on);if(on)active=row;row.querySelectorAll('.momo-word').forEach(w=>{const ws=Number(w.dataset.start),we=Number(w.dataset.end);w.classList.toggle('active',Number.isFinite(ws)&&Number.isFinite(we)&&t>=ws&&t<we)})});if(active&&active!==state.activeRow){state.activeRow=active;const q=active.getBoundingClientRect(),p=root.getBoundingClientRect();if(q.top<p.top||q.bottom>p.bottom)active.scrollIntoView({block:'center',behavior:'smooth'})}}
  async function load(force=false){const raw=readTrack();if(!raw)return;if(state.abort)state.abort.abort();state.abort=new AbortController();const signal=state.abort.signal;state.loading=true;try{const track=await resolveMetadata(raw,signal);if(signal.aborted)return;persistRecoveredMetadata(track);const meta=track.metadata||{};const key=`${meta.isrc||''}|${meta.artist||track.artist||''}|${meta.title||track.title||''}|${Math.round(Number(meta.duration||track.duration||0))}`.toLowerCase();if(!force&&key===state.trackKey&&state.lyrics){state.loading=false;return}state.trackKey=key;state.lyrics=null;state.activeRow=null;toast(track.metadataSource==='recovered'?'metadata recovered · searching lyrics…':'searching lyrics…');const m=await getManager();if(!m)throw new Error('lyrics engine unavailable');const l=await m.resolve(track,{refresh:force,signal});if(signal.aborted||key!==state.trackKey)return;if(!l){toast('no lyrics found');return}state.lyrics=l;render(l);toast(`${l.wordTiming==='native'?'real word-sync':l.format||'plain'} · ${l.source||'lyrics'}`)}catch(e){if(e?.name!=='AbortError'&&!signal.aborted){console.warn('[momo lyrics]',e);toast('lyrics lookup failed')}}finally{if(!signal.aborted)state.loading=false}}
  function install(){css();const a=document.querySelector('audio');if(a!==state.audio){state.abort?.abort();state.audio=a;state.trackKey='';state.lyrics=null;state.activeRow=null;if(a){['timeupdate','seeked','play'].forEach(e=>a.addEventListener(e,tick,{passive:true}));['loadedmetadata','durationchange'].forEach(e=>a.addEventListener(e,()=>load(false),{passive:true}));a.addEventListener('emptied',()=>{state.abort?.abort();state.trackKey='';state.lyrics=null},{passive:true})}}if(state.audio&&!state.loading)load(false)}
  await sleep(400);install();clearInterval(state.timer);state.timer=setInterval(()=>{install();tick()},2000);
})();
