/* Momoirobara experimental lyrics UI bridge. Owns the lyrics container on experimental. */
(async () => {
  'use strict';
  if (window.__momoExperimentalLyrics) return;
  window.__momoExperimentalLyrics = true;
  const state={audio:null,lyrics:null,trackKey:'',manager:null,metadataResolver:null,renderer:null,timer:0,abort:null,loading:false};
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  function findRoot(){return document.getElementById('lyr')||document.querySelector('.lyrics-drawer #lyr')||document.querySelector('.lyrics-drawer');}
  function css(){if(document.getElementById('momo-experimental-lyrics-css'))return;const s=document.createElement('style');s.id='momo-experimental-lyrics-css';s.textContent=`#lyr.momo-experimental-owned{all:initial!important;display:block!important;position:relative!important;width:100%!important;height:100%!important;min-height:0!important;box-sizing:border-box!important;color:inherit!important;background:transparent!important}#lyr.momo-experimental-owned *{box-sizing:border-box}#momoExperimentalLyricsRefresh{display:none!important}#momoExperimentalLyricsStatus{position:fixed;right:18px;bottom:24px;z-index:99997;font:500 11px system-ui;color:var(--muted,#777);pointer-events:none;opacity:0;transition:opacity .2s}#momoExperimentalLyricsStatus.show{opacity:.9}`;document.head.appendChild(s)}
  function toast(text){let e=document.getElementById('momoExperimentalLyricsStatus');if(!e){e=document.createElement('div');e.id='momoExperimentalLyricsStatus';document.body.appendChild(e)}e.textContent=text;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1800)}
  function parseFilename(url){try{const n=decodeURIComponent(new URL(url,location.href).pathname.split('/').pop()||'').replace(/\.[^.]+$/,'').replace(/[_]+/g,' ').replace(/\s+/g,' ').trim(),p=n.split(/\s+[-–—]\s+/);return p.length>=2?{artist:p[0].trim(),title:p.slice(1).join(' - ').trim()}:{title:n}}catch{return{}}}
  function readTrack(){const a=state.audio||document.querySelector('audio');if(!a)return null;state.audio=a;const songs=Array.isArray(window.momoSongs)?window.momoSongs:[],index=Number(window.momoCurrentIndex),appSong=Number.isInteger(index)&&index>=0?songs[index]:null,te=document.querySelector('[data-track-title],.now-playing .title,.player .title,.player-bar .title,[class*="now-playing"] [class*="title"]'),ae=document.querySelector('[data-track-artist],.now-playing .artist,.player .artist,.player-bar .artist'),f=parseFilename(a.currentSrc||a.src||appSong?.fileName||appSong?.path||''),base=appSong?.metadata||appSong||{},title=String(base.title||base.trackName||te?.textContent||f.title||'').trim(),artist=String(base.artist||base.artistName||ae?.textContent||f.artist||'').trim(),duration=Number(base.duration||a.duration||0);return{...appSong,fileName:appSong?.fileName||appSong?.path||a.currentSrc||a.src||'',metadata:{...base,title,artist,album:String(base.album||base.albumName||'').trim(),duration:Number.isFinite(duration)?duration:0,isrc:base.isrc||base.ISRC||''},title,artist,duration}}
  async function im(p){try{return await import(p)}catch(e){console.warn('[momo lyrics]',p,e);return null}}
  async function getManager(){if(state.manager)return state.manager;const m=await im('./manager.js');if(!m?.createLyricsManager)return null;const specs=[['./providers/lyricsplus.js','lyricsPlusProvider'],['./providers/lrclib.js','lrclibProvider'],['./providers/lrcmux.js','lrcMuxProvider']],ps=[];for(const[p,n]of specs){const x=await im(p),v=x?.default||x?.[n];if(v?.getLyrics)ps.push(v)}state.manager=m.createLyricsManager({providers:ps,delayMs:350});return state.manager}
  async function resolveMetadata(track,signal){if(!state.metadataResolver){const mod=await im('./metadata-pipeline.js');state.metadataResolver=mod?.resolveTrackForLyrics||null}return state.metadataResolver?state.metadataResolver(track,{signal}):track}
  async function getRenderer(){if(state.renderer)return state.renderer;const mod=await im('./amll-renderer.js');state.renderer=mod?.createAMLLRenderer?.()||null;return state.renderer}
  function fallback(l,track){const root=findRoot();if(!root)return;root.classList.add('momo-experimental-owned');root.innerHTML='';const box=document.createElement('div');box.style.cssText='display:flex;align-items:center;justify-content:center;height:100%;font:600 18px system-ui;opacity:.7;text-align:center';box.textContent=l?.plainLyrics||'No lyrics found.';root.appendChild(box)}
  async function render(l,track){const root=findRoot();if(!root)return;root.classList.add('momo-experimental-owned');const renderer=await getRenderer();if(!renderer?.mount||!renderer?.setLyrics){fallback(l,track);return}renderer.mount(root,{audio:state.audio});renderer.setLyrics(l,track)}
  function tick(){if(state.renderer?.update){state.renderer.update(state.audio?.currentTime||0);return}}
  async function load(force=false){const raw=readTrack();if(!raw)return;if(state.abort)state.abort.abort();state.abort=new AbortController();const signal=state.abort.signal;state.loading=true;try{const track=await resolveMetadata(raw,signal);if(signal.aborted)return;const meta=track.metadata||{},key=`${meta.isrc||''}|${meta.artist||track.artist||''}|${meta.title||track.title||''}|${Math.round(Number(meta.duration||track.duration||0))}`.toLowerCase();if(!force&&key===state.trackKey&&state.lyrics){state.loading=false;return}state.trackKey=key;state.lyrics=null;toast('finding lyrics…');const m=await getManager();if(!m)throw new Error('lyrics engine unavailable');if(signal.aborted)return;const l=await m.resolve(track,{refresh:force,signal});if(signal.aborted||key!==state.trackKey)return;if(!l){toast('no lyrics found');return}state.lyrics=l;await render(l,track);toast(`${l.wordTiming==='native'?'word-synced':l.format||'plain'} lyrics`)}catch(e){if(e?.name!=='AbortError'&&!signal.aborted){console.warn('[momo lyrics]',e);toast('lyrics lookup failed')}}finally{if(!signal.aborted)state.loading=false}}
  function install(){css();const root=findRoot();if(root)root.classList.add('momo-experimental-owned');const a=document.querySelector('audio');if(a!==state.audio){if(state.audio&&state.abort)state.abort.abort();state.audio=a;state.trackKey='';state.lyrics=null;if(a){['timeupdate','seeked','play'].forEach(e=>a.addEventListener(e,tick,{passive:true}));['loadedmetadata','durationchange'].forEach(e=>a.addEventListener(e,()=>load(false),{passive:true}));a.addEventListener('emptied',()=>{state.abort?.abort();state.trackKey='';state.lyrics=null},{passive:true})}}if(state.audio&&!state.loading)load(false)}
  await sleep(400);install();clearInterval(state.timer);state.timer=setInterval(()=>{install();tick()},2000);
})();
